### ISSUE TITLE
error on importing legacy wurst project 

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstSetup#2]
see https://github.com/wurstscript/WurstScript/issues/609

**Comment by DDLegionTN** [comment]
wurst.build :

```
---
projectName: "DefaultName"
dependencies:
- "https://github.com/wurstscript/wurstStdlib2"
buildMapData:
  name: "DefaultName"
  fileName: "DefaultFileName"
  author: "DefaultAuthor"

```
